CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace TEXT NOT NULL,
    document_name TEXT NOT NULL,
    current_structure_version INTEGER NOT NULL CHECK (current_structure_version >= 1),
    status TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_documents_namespace_document_name UNIQUE (namespace, document_name)
);

CREATE TABLE IF NOT EXISTS raw_source_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE,
    source_location TEXT NOT NULL,
    original_filename TEXT,
    mime_type TEXT,
    file_size BIGINT,
    checksum TEXT,
    ownership_scope TEXT,
    metadata_payload JSONB,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS document_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE,
    profile_payload JSONB NOT NULL,
    profile_version TEXT,
    schema_version TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_parser TEXT,
    preparation_mode TEXT,
    language_metadata JSONB,
    title_metadata JSONB,
    author_metadata JSONB,
    source_metadata JSONB,
    source_structure_version INTEGER CHECK (
        source_structure_version IS NULL OR source_structure_version >= 1
    ),
    advisory_diagnostics JSONB
);

CREATE TABLE IF NOT EXISTS parse_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('initial_parse', 'hard_reparse')),
    previous_structure_version INTEGER,
    new_structure_version INTEGER NOT NULL CHECK (new_structure_version >= 1),
    trigger_source TEXT,
    parser_mode TEXT,
    reparse_reason TEXT,
    invalidated_artifact_count INTEGER,
    invalidated_content_block_count INTEGER,
    metadata_payload JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_order INTEGER NOT NULL,
    reference_chapter_id TEXT,
    title TEXT,
    level INTEGER NOT NULL,
    chapter_role TEXT,
    source_anchor JSONB,
    metadata_payload JSONB,
    CONSTRAINT uq_chapters_document_order UNIQUE (document_id, chapter_order)
);

CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    section_order INTEGER NOT NULL,
    reference_section_id TEXT,
    title TEXT,
    level INTEGER NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    char_start INTEGER NOT NULL DEFAULT 0,
    char_end INTEGER NOT NULL DEFAULT 0,
    container_title TEXT,
    section_role TEXT,
    section_kind TEXT,
    is_implicit_section BOOLEAN NOT NULL DEFAULT FALSE,
    source_anchor JSONB,
    metadata_payload JSONB,
    CONSTRAINT uq_sections_chapter_order UNIQUE (chapter_id, section_order)
);

CREATE TABLE IF NOT EXISTS task_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    section_id BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    task_unit_order INTEGER NOT NULL,
    reference_unit_id TEXT,
    title TEXT,
    container_title TEXT,
    content_payload TEXT NOT NULL DEFAULT '',
    source_section_ids_payload JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_fallback_generated BOOLEAN NOT NULL DEFAULT FALSE,
    metadata_payload JSONB,
    CONSTRAINT uq_task_units_section_order UNIQUE (section_id, task_unit_order)
);


CREATE TABLE IF NOT EXISTS content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    task_unit_id BIGINT NOT NULL REFERENCES task_units(id) ON DELETE CASCADE,
    block_order INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    source_hash TEXT,
    segmentation_version TEXT,
    quote_span_start INTEGER,
    quote_span_end INTEGER,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_content_blocks_span_order CHECK (
        quote_span_start IS NULL
        OR quote_span_end IS NULL
        OR quote_span_start <= quote_span_end
    )
);

CREATE TABLE IF NOT EXISTS artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL,
    target_type TEXT NOT NULL CHECK (
        target_type IN ('document', 'chapter', 'section', 'task_unit', 'content_block')
    ),
    target_id BIGINT NOT NULL,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    source_hash TEXT,
    quote_span_start INTEGER,
    quote_span_end INTEGER,
    payload JSONB NOT NULL,
    schema_version TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT ck_artifacts_span_order CHECK (
        quote_span_start IS NULL
        OR quote_span_end IS NULL
        OR quote_span_start <= quote_span_end
    )
);

CREATE TABLE IF NOT EXISTS structured_document_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    structured_document_payload JSONB NOT NULL,
    schema_version TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_structured_document_snapshots_document_version
        UNIQUE (document_id, source_structure_version)
);

CREATE INDEX IF NOT EXISTS idx_raw_source_metadata_document_id
    ON raw_source_metadata(document_id);

CREATE INDEX IF NOT EXISTS idx_documents_namespace_document_name
    ON documents(namespace, document_name);

CREATE INDEX IF NOT EXISTS idx_document_profile_document_id
    ON document_profile(document_id);

CREATE INDEX IF NOT EXISTS idx_document_profile_document_id_source_structure_version
    ON document_profile(document_id, source_structure_version);

CREATE INDEX IF NOT EXISTS idx_parse_events_document_id_occurred_at
    ON parse_events(document_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_parse_events_document_id_new_structure_version
    ON parse_events(document_id, new_structure_version);

CREATE INDEX IF NOT EXISTS idx_chapters_document_id_order
    ON chapters(document_id, chapter_order);

CREATE INDEX IF NOT EXISTS idx_sections_document_id_chapter_id_order
    ON sections(document_id, chapter_id, section_order);

CREATE INDEX IF NOT EXISTS idx_sections_chapter_id
    ON sections(chapter_id);

CREATE INDEX IF NOT EXISTS idx_task_units_document_id_section_id_order
    ON task_units(document_id, section_id, task_unit_order);

CREATE INDEX IF NOT EXISTS idx_task_units_section_id
    ON task_units(section_id);

CREATE INDEX IF NOT EXISTS idx_content_blocks_document_id_task_unit_id_order
    ON content_blocks(document_id, task_unit_id, block_order);

CREATE INDEX IF NOT EXISTS idx_content_blocks_document_id_source_structure_version
    ON content_blocks(document_id, source_structure_version);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_artifact_type
    ON artifacts(document_id, artifact_type);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_target
    ON artifacts(document_id, target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_source_structure_version
    ON artifacts(document_id, source_structure_version);

CREATE INDEX IF NOT EXISTS idx_artifacts_created_at
    ON artifacts(created_at);

CREATE INDEX IF NOT EXISTS idx_structured_document_snapshots_document_id_version
    ON structured_document_snapshots(document_id, source_structure_version);
