-- Timestamp ownership policy:
-- updated_at fields are application-managed. PostgreSQL supplies insert defaults
-- where declared, but update statements must explicitly set updated_at = NOW().
-- No trigger in this migration updates timestamps or domain lifecycle state.
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace TEXT NOT NULL,
    document_name TEXT NOT NULL,
    current_structure_version INTEGER NOT NULL CHECK (current_structure_version >= 1),
    status TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_documents_namespace_document_name UNIQUE (namespace, document_name)
);

CREATE TABLE IF NOT EXISTS raw_source_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE,
    source_location TEXT NOT NULL,
    original_filename TEXT,
    mime_type TEXT,
    file_size BIGINT,
    checksum TEXT,
    ownership_scope TEXT,
    metadata_payload JSONB,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_raw_source_metadata_file_size_non_negative CHECK (
        file_size IS NULL OR file_size >= 0
    )
);

CREATE TABLE IF NOT EXISTS document_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id) ON DELETE CASCADE,
    profile_payload JSONB NOT NULL,
    profile_version TEXT,
    schema_version TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_parser TEXT,
    preparation_mode TEXT,
    language_metadata JSONB,
    title_metadata JSONB,
    author_metadata JSONB,
    source_metadata JSONB,
    source_structure_version INTEGER CHECK (
        source_structure_version IS NULL OR source_structure_version >= 1
    ),
    advisory_diagnostics JSONB
);

CREATE TABLE IF NOT EXISTS parse_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('initial_parse', 'hard_reparse')),
    previous_structure_version INTEGER,
    new_structure_version INTEGER NOT NULL CHECK (new_structure_version >= 1),
    trigger_source TEXT,
    parser_mode TEXT,
    reparse_reason TEXT,
    invalidated_artifact_count INTEGER,
    invalidated_content_block_count INTEGER,
    metadata_payload JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_parse_events_initial_parse_versions CHECK (
        event_type <> 'initial_parse'
        OR (
            previous_structure_version IS NULL
            AND new_structure_version = 1
        )
    ),
    CONSTRAINT ck_parse_events_initial_parse_no_reparse_metadata CHECK (
        event_type <> 'initial_parse'
        OR (
            reparse_reason IS NULL
            AND (
                invalidated_artifact_count IS NULL
                OR invalidated_artifact_count = 0
            )
            AND (
                invalidated_content_block_count IS NULL
                OR invalidated_content_block_count = 0
            )
        )
    ),
    CONSTRAINT ck_parse_events_hard_reparse_versions CHECK (
        event_type <> 'hard_reparse'
        OR (
            previous_structure_version IS NOT NULL
            AND previous_structure_version >= 1
            AND new_structure_version = previous_structure_version + 1
        )
    ),
    CONSTRAINT ck_parse_events_invalidation_counts_non_negative CHECK (
        (
            invalidated_artifact_count IS NULL
            OR invalidated_artifact_count >= 0
        )
        AND (
            invalidated_content_block_count IS NULL
            OR invalidated_content_block_count >= 0
        )
    )
);

CREATE TABLE IF NOT EXISTS chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_order INTEGER NOT NULL,
    reference_chapter_id TEXT,
    title TEXT,
    level INTEGER NOT NULL,
    chapter_role TEXT,
    source_anchor JSONB,
    metadata_payload JSONB,
    CONSTRAINT ck_chapters_order_non_negative CHECK (chapter_order >= 0),
    CONSTRAINT uq_chapters_document_order UNIQUE (document_id, chapter_order),
    CONSTRAINT uq_chapters_id_document UNIQUE (id, document_id)
);

CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    chapter_id BIGINT NOT NULL,
    section_order INTEGER NOT NULL,
    reference_section_id TEXT,
    title TEXT,
    level INTEGER NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    char_start INTEGER NOT NULL DEFAULT 0,
    char_end INTEGER NOT NULL DEFAULT 0,
    container_title TEXT,
    section_role TEXT,
    section_kind TEXT,
    is_implicit_section BOOLEAN NOT NULL DEFAULT FALSE,
    source_anchor JSONB,
    metadata_payload JSONB,
    CONSTRAINT ck_sections_order_non_negative CHECK (section_order >= 0),
    CONSTRAINT ck_sections_char_span_non_negative CHECK (
        char_start >= 0 AND char_end >= 0
    ),
    CONSTRAINT ck_sections_char_span_order CHECK (char_start <= char_end),
    CONSTRAINT uq_sections_chapter_order UNIQUE (chapter_id, section_order),
    CONSTRAINT uq_sections_id_document UNIQUE (id, document_id),
    CONSTRAINT fk_sections_chapter_document
        FOREIGN KEY (chapter_id, document_id)
        REFERENCES chapters(id, document_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    section_id BIGINT NOT NULL,
    task_unit_order INTEGER NOT NULL,
    reference_unit_id TEXT,
    title TEXT,
    container_title TEXT,
    content_payload TEXT NOT NULL DEFAULT '',
    source_section_ids_payload JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_fallback_generated BOOLEAN NOT NULL DEFAULT FALSE,
    metadata_payload JSONB,
    CONSTRAINT ck_task_units_order_non_negative CHECK (task_unit_order >= 0),
    CONSTRAINT uq_task_units_section_order UNIQUE (section_id, task_unit_order),
    CONSTRAINT uq_task_units_id_document UNIQUE (id, document_id),
    CONSTRAINT fk_task_units_section_document
        FOREIGN KEY (section_id, document_id)
        REFERENCES sections(id, document_id)
        ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    task_unit_id BIGINT NOT NULL,
    block_order INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    source_hash TEXT,
    segmentation_version TEXT,
    quote_span_start INTEGER,
    quote_span_end INTEGER,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_content_blocks_order_non_negative CHECK (block_order >= 0),
    CONSTRAINT ck_content_blocks_quote_span_non_negative CHECK (
        (quote_span_start IS NULL OR quote_span_start >= 0)
        AND (quote_span_end IS NULL OR quote_span_end >= 0)
    ),
    CONSTRAINT ck_content_blocks_quote_span_order CHECK (
        quote_span_start IS NULL
        OR quote_span_end IS NULL
        OR quote_span_start <= quote_span_end
    ),
    CONSTRAINT fk_content_blocks_task_unit_document
        FOREIGN KEY (task_unit_id, document_id)
        REFERENCES task_units(id, document_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL,
    target_type TEXT NOT NULL CHECK (
        target_type IN ('document', 'chapter', 'section', 'task_unit', 'content_block')
    ),
    target_id BIGINT NOT NULL,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    source_hash TEXT,
    quote_span_start INTEGER,
    quote_span_end INTEGER,
    payload JSONB NOT NULL,
    schema_version TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Nullable until the first application-managed artifact mutation.
    updated_at TIMESTAMPTZ,
    CONSTRAINT ck_artifacts_quote_span_non_negative CHECK (
        (quote_span_start IS NULL OR quote_span_start >= 0)
        AND (quote_span_end IS NULL OR quote_span_end >= 0)
    ),
    CONSTRAINT ck_artifacts_quote_span_order CHECK (
        quote_span_start IS NULL
        OR quote_span_end IS NULL
        OR quote_span_start <= quote_span_end
    )
);

CREATE TABLE IF NOT EXISTS structured_document_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    source_structure_version INTEGER NOT NULL CHECK (source_structure_version >= 1),
    structured_document_payload JSONB NOT NULL,
    schema_version TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_structured_document_snapshots_document_version
        UNIQUE (document_id, source_structure_version)
);

CREATE INDEX IF NOT EXISTS idx_parse_events_document_id_occurred_at
    ON parse_events(document_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_parse_events_document_id_new_structure_version
    ON parse_events(document_id, new_structure_version);

CREATE INDEX IF NOT EXISTS idx_sections_document_id_chapter_id_order
    ON sections(document_id, chapter_id, section_order);

CREATE INDEX IF NOT EXISTS idx_task_units_document_id_section_id_order
    ON task_units(document_id, section_id, task_unit_order);

CREATE INDEX IF NOT EXISTS idx_content_blocks_document_id_task_unit_id_order
    ON content_blocks(document_id, task_unit_id, block_order);

CREATE INDEX IF NOT EXISTS idx_content_blocks_document_id_source_structure_version
    ON content_blocks(document_id, source_structure_version);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_artifact_type
    ON artifacts(document_id, artifact_type);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_target
    ON artifacts(document_id, target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_artifacts_document_id_source_structure_version
    ON artifacts(document_id, source_structure_version);
