CREATE TABLE IF NOT EXISTS ocr_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    source_file_sha256 TEXT NOT NULL,
    ocr_engine TEXT NOT NULL,
    ocr_engine_version TEXT,
    ocr_language TEXT NOT NULL,
    renderer TEXT,
    render_dpi INTEGER,
    page_count INTEGER NOT NULL CHECK (page_count >= 0),
    page_limit INTEGER,
    status TEXT NOT NULL,
    full_text TEXT,
    metadata_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ocr_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocr_run_id BIGINT NOT NULL REFERENCES ocr_runs(id) ON DELETE CASCADE,
    page_index INTEGER NOT NULL CHECK (page_index >= 0),
    text TEXT NOT NULL DEFAULT '',
    metadata_payload JSONB,
    UNIQUE (ocr_run_id, page_index)
);

CREATE INDEX IF NOT EXISTS idx_ocr_runs_document_created_at
    ON ocr_runs(document_id, created_at);

CREATE INDEX IF NOT EXISTS idx_ocr_pages_run_page
    ON ocr_pages(ocr_run_id, page_index);
