from language.language_code import LanguageCode


class QuestionScopeKeywordsProvider:
    """Provide global-scope intent keywords by language."""

    _KEYWORDS: dict[LanguageCode, tuple[str, ...]] = {
        LanguageCode.EN: (
            "which",
            "what are the main",
            "major",
            "all",
            "list",
            "overall",
            "themes",
            "relationships",
            "reasons",
            "summarize",
            "in the whole book",
            "across the document",
        ),
        LanguageCode.ZH: (
            "哪些",
            "主要",
            "總結",
            "总结",
            "整體",
            "整体",
            "全書",
            "全书",
            "整篇",
            "原因有哪些",
            "關係有哪些",
            "关系有哪些",
            "主題",
            "主题",
            "列舉",
            "列举",
            "歸納",
            "归纳",
        ),
        LanguageCode.JA: (
            "どの",
            "主な",
            "全体",
            "全書",
            "一覧",
            "要約",
            "テーマ",
            "関係",
            "理由",
        ),
        LanguageCode.KO: (
            "어떤",
            "주요",
            "전체",
            "전반",
            "목록",
            "요약",
            "주제",
            "관계",
            "이유",
        ),
        LanguageCode.ES: (
            "cuáles",
            "principales",
            "todo",
            "lista",
            "general",
            "temas",
            "relaciones",
            "razones",
            "resumen",
        ),
        LanguageCode.PT: (
            "quais",
            "principais",
            "tudo",
            "lista",
            "geral",
            "temas",
            "relacionamentos",
            "razões",
            "resumo",
        ),
        LanguageCode.FR: (
            "quels",
            "principaux",
            "tous",
            "liste",
            "global",
            "thèmes",
            "relations",
            "raisons",
            "résumé",
        ),
        LanguageCode.DE: (
            "welche",
            "haupt",
            "alle",
            "liste",
            "insgesamt",
            "themen",
            "beziehungen",
            "gründe",
            "zusammenfassung",
        ),
        LanguageCode.IT: (
            "quali",
            "principali",
            "tutti",
            "elenco",
            "complessivo",
            "temi",
            "relazioni",
            "ragioni",
            "riassunto",
        ),
        LanguageCode.RU: (
            "какие",
            "основные",
            "все",
            "список",
            "в целом",
            "темы",
            "отношения",
            "причины",
            "сводка",
        ),
        LanguageCode.AR: (
            "ما هي الرئيسية",
            "الرئيسية",
            "كل",
            "قائمة",
            "بشكل عام",
            "الموضوعات",
            "العلاقات",
            "الأسباب",
            "ملخص",
        ),
        LanguageCode.HI: (
            "मुख्य",
            "कौन से",
            "सभी",
            "सूची",
            "समग्र",
            "थीम",
            "संबंध",
            "कारण",
            "सारांश",
        ),
        LanguageCode.TR: (
            "hangi",
            "ana",
            "tümü",
            "liste",
            "genel",
            "temalar",
            "ilişkiler",
            "nedenler",
            "özet",
        ),
        LanguageCode.NL: (
            "welke",
            "belangrijkste",
            "alle",
            "lijst",
            "algemeen",
            "thema's",
            "relaties",
            "redenen",
            "samenvatting",
        ),
        LanguageCode.PL: (
            "które",
            "główne",
            "wszystkie",
            "lista",
            "ogólnie",
            "tematy",
            "relacje",
            "powody",
            "podsumowanie",
        ),
        LanguageCode.UK: (
            "які",
            "основні",
            "усі",
            "список",
            "загалом",
            "теми",
            "стосунки",
            "причини",
            "підсумок",
        ),
        LanguageCode.ID: (
            "yang",
            "utama",
            "semua",
            "daftar",
            "secara keseluruhan",
            "tema",
            "hubungan",
            "alasan",
            "ringkasan",
        ),
        LanguageCode.VI: (
            "những",
            "chính",
            "tất cả",
            "liệt kê",
            "tổng thể",
            "chủ đề",
            "mối quan hệ",
            "lý do",
            "tóm tắt",
        ),
        LanguageCode.TH: (
            "อะไรบ้าง",
            "หลัก",
            "ทั้งหมด",
            "รายการ",
            "โดยรวม",
            "ธีม",
            "ความสัมพันธ์",
            "เหตุผล",
            "สรุป",
        ),
    }

    def get_keywords(self, language: LanguageCode) -> tuple[str, ...]:
        """Return global-intent keywords for a specific language code."""
        if language in self._KEYWORDS:
            return self._KEYWORDS[language]
        return self._KEYWORDS[LanguageCode.EN]

    def get_all_keywords(self) -> tuple[str, ...]:
        """Return deduplicated keyword set across all supported languages."""
        seen: set[str] = set()
        ordered: list[str] = []
        for values in self._KEYWORDS.values():
            for value in values:
                if value in seen:
                    continue
                seen.add(value)
                ordered.append(value)
        return tuple(ordered)
