from llama_index.llms.openai import OpenAI
from llama_index.llms.openai.responses import OpenAIResponses

from api_key_provider import APIKeyProvider
from llm_model_capabilities import (
    ENDPOINT_KIND_CHAT_COMPLETIONS,
    ENDPOINT_KIND_RESPONSES,
    LLMModelCapabilities,
)
from llm_provider import LLMProvider


class OpenAILLMProvider(LLMProvider):
    """LLMProvider implementation backed by OpenAI via llama-index."""
    llm: OpenAI | OpenAIResponses
    model_capabilities: LLMModelCapabilities
    effective_output_budget: int

    MODEL_CAPABILITIES_BY_NAME: dict[str, LLMModelCapabilities] = {
        "gpt-4.1": LLMModelCapabilities(
            model_name="gpt-4.1",
            endpoint_kind=ENDPOINT_KIND_RESPONSES,
            max_input_tokens=1_047_576,
            max_output_tokens=32_768,
        ),
        "gpt-4.1-mini": LLMModelCapabilities(
            model_name="gpt-4.1-mini",
            endpoint_kind=ENDPOINT_KIND_RESPONSES,
            max_input_tokens=1_047_576,
            max_output_tokens=32_768,
        ),
        "gpt-4.1-nano": LLMModelCapabilities(
            model_name="gpt-4.1-nano",
            endpoint_kind=ENDPOINT_KIND_RESPONSES,
            max_input_tokens=1_047_576,
            max_output_tokens=32_768,
        ),
        "gpt-4o": LLMModelCapabilities(
            model_name="gpt-4o",
            endpoint_kind=ENDPOINT_KIND_CHAT_COMPLETIONS,
            max_input_tokens=128_000,
            max_output_tokens=16_384,
        ),
        "gpt-4o-mini": LLMModelCapabilities(
            model_name="gpt-4o-mini",
            endpoint_kind=ENDPOINT_KIND_CHAT_COMPLETIONS,
            max_input_tokens=128_000,
            max_output_tokens=16_384,
        ),
    }

    @classmethod
    def _resolve_model_capabilities(cls, model: str) -> LLMModelCapabilities:
        capabilities = cls.MODEL_CAPABILITIES_BY_NAME.get(model)
        if capabilities is None:
            supported = ", ".join(sorted(cls.MODEL_CAPABILITIES_BY_NAME.keys()))
            raise ValueError(
                f"Unsupported llm model '{model}'. "
                f"Supported models: {supported}"
            )
        return capabilities

    def __init__(
        self,
        api_key_provider: APIKeyProvider,
        model: str = "gpt-4.1-mini",
        target_max_output_tokens: int = 500,
    ):
        """Initialize object state and injected dependencies.

Args:
    api_key_provider: Api key provider.
    model: Model.
    target_max_output_tokens: App-level output-token target before model clamp.
"""
        api_key = api_key_provider.get()
        self.model_capabilities = self._resolve_model_capabilities(model)
        if target_max_output_tokens <= 0:
            raise ValueError("target_max_output_tokens must be > 0")
        self.effective_output_budget = min(
            target_max_output_tokens,
            self.model_capabilities.max_output_tokens,
        )

        if self.model_capabilities.endpoint_kind == ENDPOINT_KIND_RESPONSES:
            self.llm = OpenAIResponses(
                model=model,
                api_key=api_key,
            )
        else:
            self.llm = OpenAI(
                model=model,
                api_key=api_key,
            )

        print(
            "OpenAILLMProvider#init:",
            f"model={self.model_capabilities.model_name}",
            f"endpoint_kind={self.model_capabilities.endpoint_kind}",
            f"max_input_tokens={self.model_capabilities.max_input_tokens}",
            f"max_output_tokens={self.model_capabilities.max_output_tokens}",
            f"effective_output_budget={self.effective_output_budget}",
        )

    def complete_text(self, prompt: str) -> str:
        """Call underlying completion backend and return generated text.

Args:
    prompt: Prompt text sent to completion model.

Returns:
    Trimmed text completion generated by the OpenAI model."""
        print("OpenAI LLM:prompt", prompt)
        if self.model_capabilities.endpoint_kind == ENDPOINT_KIND_RESPONSES:
            response = self.llm.complete(
                prompt,
                max_output_tokens=self.effective_output_budget,
            )
        else:
            response = self.llm.complete(
                prompt,
                max_completion_tokens=self.effective_output_budget,
            )
        return response.text.strip()

    def get_model_capabilities(self) -> LLMModelCapabilities:
        """Return current model static capability metadata."""
        return self.model_capabilities
