from llama_index.llms.openai import OpenAI

from api_key_provider import APIKeyProvider
from llm_provider import LLMProvider


class OpenAILLMProvider(LLMProvider):
    """LLMProvider implementation backed by OpenAI via llama-index."""
    llm: OpenAI

    def __init__(self, api_key_provider: APIKeyProvider, model: str = "gpt-4.1-mini"):
        """Initialize object state and injected dependencies.

Args:
    api_key_provider: Api key provider.
    model: Model.
"""
        api_key = api_key_provider.get()

        self.llm = OpenAI(
            model=model,
            api_key=api_key,
        )

    def complete_text(self, prompt: str) -> str:
        """Call underlying completion backend and return generated text.

Args:
    prompt: Prompt text sent to completion model.

Returns:
    Trimmed text completion generated by the OpenAI model."""
        print("OpenAI LLM:prompt", prompt)
        response = self.llm.complete(prompt)
        return response.text.strip()
