#!/usr/bin/env python3
"""Static validation for the Phase 1 PostgreSQL migration shape."""

from __future__ import annotations

import json
from pathlib import Path


MIGRATION_PATH = (
    Path(__file__).resolve().parents[1]
    / "db"
    / "migrations"
    / "001_phase_1_core_hierarchy.sql"
)


def _assert(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def test_postgresql_migration_shape() -> None:
    sql = MIGRATION_PATH.read_text(encoding="utf-8")
    lowered = sql.lower()

    _assert("pragma" not in lowered, "PostgreSQL migration must not use SQLite PRAGMA")
    _assert(
        "autoincrement" not in lowered,
        "PostgreSQL migration must not use SQLite AUTOINCREMENT",
    )
    _assert(
        "generated by default as identity" in lowered,
        "PostgreSQL migration should use DB-generated identity columns",
    )
    _assert("jsonb" in lowered, "PostgreSQL migration should use JSONB payloads")
    _assert(
        "timestamptz" in lowered,
        "PostgreSQL migration should use timestamptz timestamps",
    )
    _assert("boolean" in lowered, "PostgreSQL migration should use boolean fields")

    for table_name in (
        "documents",
        "raw_source_metadata",
        "document_profile",
        "parse_events",
        "chapters",
        "sections",
        "task_units",
        "content_blocks",
        "artifacts",
        "structured_document_snapshots",
    ):
        _assert(
            f"create table if not exists {table_name}" in lowered,
            f"missing table: {table_name}",
        )

    _assert(
        "unique (namespace, document_name)" in lowered,
        "documents must keep namespace/document_name uniqueness",
    )
    _assert(
        "source_section_ids_payload jsonb not null default '[]'::jsonb" in lowered,
        "task_units should use JSONB source_section_ids payload in PostgreSQL",
    )
    _assert(
        "content_payload text not null default ''" in lowered,
        "task_units should keep text content_payload for Phase 1 readback",
    )
    _assert(
        "profile_payload jsonb not null" in lowered,
        "document_profile should persist advisory profile JSONB payload",
    )
    _assert(
        "task_unit_id bigint not null references task_units(id) on delete cascade"
        in lowered,
        "content_blocks should be linked to task_units",
    )
    _assert(
        "target_type text not null check" in lowered,
        "artifacts should keep polymorphic target validation metadata",
    )
    _assert(
        "payload jsonb not null" in lowered,
        "artifacts should use type-specific JSONB payloads",
    )
    _assert(
        "structured_document_payload jsonb not null" in lowered,
        "structured_document_snapshots should be JSONB parity artifacts",
    )
    _assert(
        "create table if not exists summary_artifacts" not in lowered,
        "Phase 1 must not introduce category-specific artifact tables",
    )


def main() -> None:
    test_postgresql_migration_shape()
    print(
        json.dumps(
            {
                "status": "ok",
                "tests": ["db_phase_1_postgresql_migration_shape"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
